spring:
  application:
    name: underwriting_service
  
  profiles:
    active: local

  mongodb:
    uri: mongodb://localhost:27017/underwriting_db
  
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  signing_key: ${JWT_SECRET_KEY}
  
server:
  port: 7777